account_button = '[class="css-1tef76f"]'
login_button = 'button[data-at="login-btn"]'
cont_number = '[aria-label ="Mobile number"]'
submit_button = 'button[type="submit"]'
verify_otp = 'button[type="submit"]'
wrong_otp_number = '[class="css-132pekl"] span'
