pincode = '[aria-label="Pincode*"]'
address_line_1 = '[aria-label="Address line 1*"]'
address_line_2 = '[aria-label="Address line 2*"]'
full_name = '[aria-label="Full Name*"]'
phone_number = '[aria-label="Phone Number*"]'
save_button = 'button[type="submit"]'
